-- Generated by set-wallpaper. Do not edit by hand.
return {
    accent   = "rgba(68afd9ff)",
    dim      = "rgba(5d88a2ff)",
    muted    = "rgba(3b4b54ff)",
    bg       = "rgba(0f1315ff)",
    bg_plain = "rgb(0f1315)",
    accent_plain = "rgb(68afd9)",
    dim_plain    = "rgb(5d88a2)",
}
